services:
  - type: web
    name: whatsapp-geo-redirect
    env: node
    plan: starter
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: ADMIN_TOKEN
        sync: false
      - key: IPINFO_TOKEN
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: whatsapp-redis
          property: connectionString
    autoDeploy: true
    healthCheckPath: "/"

  - type: redis
    name: whatsapp-redis
    ipAllowList: [] # public
    plan: starter
